---
title: "R Notebook"
output: html_notebook
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = '/Users/zachstone/Documents/coursework/NYCDSA/R_project')
```

```{r}
library(polyCub)
library(sp)
library(raster)
library(rjson)
library(geojsonio)
```
```{r}
spdf <- geojson_read('./data/census2020.json', what = 'sp')
```

```{r}
block.poly = spdf[2,]@polygons[[1]]@Polygons[[1]]
```

```{r}
spdf[2,]@polygons
```

```{r}
f <- function (s, sigma = 5) exp(-rowSums(s^2)/2/sigma^2) / (2*pi*sigma^2)
```

```{r}
input = matrix(ncol = 2, nrow = 2, data = c(1,2,3,4))
f(input)
```

```{r}
polyCub(block.poly, f)
```
```{r}
#check weird cases
g = function(s) 1
polyCub(block.poly,g)
```
```{r}
point = c(-73.98450, 40.70952)
point.distance <- function(s) {sqrt(rowSums((s - point)^2))}

polyCub(spdf[2,],point.distance)
```

```{r}

plot(spdf[2,])
spdf[2,]$Shape__Area
point.sp = SpatialPoints(matrix(ncol = 2, nrow = 1, data = point), proj4string = CRS('+proj=longlat +datum=WGS84 +no_defs'))

point.dist2 <- function(s) {spDistsN1(s, pt = point.sp, longlat = TRUE)}
point.dist2(block.poly@coords)

polyCub(Polygon(block.poly@coords),point.dist2)
polyCub(block.poly,point.dist2)
```


Expected results with regular geometry

```{r}
x1 = c(0,1,1,0,0)
y1 = c(0, 0, 1, 1, 0)
square = cbind(x1,y1)
sq.poly = Polygon(square)
X.ps = Polygons(list(sq.poly), ID = 'X')
X = SpatialPolygons(list(X.ps))
plot(X)

polyCub(X,g)
```

```{r}
test.point = SpatialPoints(matrix(ncol = 2, nrow = 1, data = c(.5,.5)))
point.dist3 <- function(s) {spDistsN1(s, pt = test.point)}
point.dist3(square)

polyCub(X,function(s) {rowSums(s^2)})
polyCub(X,point.dist3)
```



